name: Build Test

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build-debian-testing:
    name: Debian Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Create Build Environment
      run: cd tests/ci/ && podman build -t asgen -f ./Dockerfile-debian-testing .

    - name: Build
      run: podman run -a stdout -a stderr -e CXX=g++ -v `pwd`:/build asgen
           ./tests/ci/run-build.sh

    - name: Tests
      run: podman run -a stdout -a stderr -e CXX=g++ -v `pwd`:/build asgen
           ./tests/ci/run-tests.sh


  build-debian-stable:
    name: Debian Stable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Create Build Environment
      run: cd tests/ci/ && podman build -t asgen -f ./Dockerfile-debian-stable .

    - name: Build
      run: podman run -a stdout -a stderr -e CXX=g++ -v `pwd`:/build asgen
           ./tests/ci/run-build.sh

    - name: Tests
      run: podman run -a stdout -a stderr -e CXX=g++ -v `pwd`:/build asgen
           ./tests/ci/run-tests.sh


  build-fedora-latest:
    name: Fedora Latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Create Build Environment
      run: cd tests/ci/ && podman build -t asgen -f ./Dockerfile-fedora-latest .

    - name: Build
      run: podman run -a stdout -a stderr -e CXX=g++ -v `pwd`:/build asgen
           ./tests/ci/run-build.sh

    - name: Tests
      run: podman run -a stdout -a stderr -e CXX=g++ -v `pwd`:/build asgen
           ./tests/ci/run-tests.sh


  build-ubuntu-lts:
    name: Ubuntu LTS
    runs-on: ubuntu-24.04
    env:
      CC: gcc-14
      CXX: g++-14
    steps:
    - uses: actions/checkout@v5

    - name: Create Build Environment
      run: sudo ./tests/ci/install-deps-deb.sh

    - name: Make & Install 3rd-party
      run: sudo ./tests/ci/ci-install-extern.sh

    - name: Build
      run: ./tests/ci/run-build.sh

    - name: Tests
      run: ./tests/ci/run-tests.sh
